### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by keul** [collective/collective.portlet.calendar#4]
Can we have a new release? The master is full of fixes needed for work properly on Plone 4.2 and 4.3.

**Comment by hvelarde** [comment]
yes, but I want he tests passing on both Plone versions before and I have no time to fix the setup now.

can you help me with that or can you wait?

**Comment by keul** [comment]
You mean the failing travis test on Plone 4.3?
Yep, I can look into this in next few days

**Comment by keul** [comment]
@hvelarde so... can we have a new release *now*? :smile:

**Comment by hvelarde** [comment]
@keul you're now a maintainer; feel free to release :beer:

**Comment by keul** [comment]
@hvelarde thanks!

**Comment by keul** [comment]
@hvelarde done, only I don't have any power on plone.org so the add-on is not updated there

**Comment by hvelarde** [comment]
never mind; now you have.
