### ISSUE TITLE
review_state filter when root object is Collection or Folder

### ISSUE THREAD

**Issue by keul** [collective/collective.portlet.calendar#5]
I'm the one who added the Collection support but I'd like to discuss a behavior that is not much clear (in any case I think I will add two lines of documentation fo the README).
I'm asking because I'm working of some issues of the product and it's a good moment for cleaning up things.

You know that:
* default calendar use a review_state filter taken from PortalCalendarTool
* this portlet gives an optional review_state filter

Which behavior is expected with folder as root ?
======================================

If I provide a folder as root object and I don't provide any review_state filter what is the more logical behavior? Should I use the CalendarTool settings (as it's doing now)?
This not seems very user friendly to me... the most logical behavior IMHO is don't use any review_state filter.

Comments?

Which behavior is expected with collection as root ?
======================================

Similar as above: when using a collection the review_state filter in portlet is not used.
But if I don't provide any review_state filter in the collection what is the expected behavior?

Right now a strange ["published", "private"] default is used (don't know why... why not the CalendarTool default?) but isn't more logical to do not use any review_state filter at all?

**Comment by keul** [comment]
Nobody can help me evaluate this? I'm working on this add-on and I want to clear-up this confusing behavior

**Comment by hvelarde** [comment]
@keul sorry, out of my reach; @ericof @rodfersou ?

**Comment by rodfersou** [comment]
@keul for me the behavior you suggested makes all sense.
